"$schema" = 'https://starship.rs/config-schema.json'

format = """
(bold overlay1)$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$docker_context\
$line_break$character"""

palette = 'nord'

[palettes.nord]
rosewater = "#f2d7a0"
flamingo = "#d78787"
pink = "#c7a8cc"
orange = "#e0a96d"
red = "#d57780"
maroon = "#a85d5d"
peach = "#e6a07c"
yellow = "#f2d7a0"
green = "#9fc6c1"
teal = "#95c1bb"
sky = "#9bbcd1"
sapphire = "#7da2bf"
blue = "#6c8ebf"
lavender = "#c0a9c7"
text = "#dce0e8"
subtext1 = "#e6e9ef"
subtext0 = "#f0f1f5"
overlay2 = "#4f5b6e"
overlay1 = "#20A7DB"
overlay0 = "#3c4454"
surface2 = "#2f3542"
surface1 = "#2c313c"
surface0 = "#282c34"
base = "#252932"
mantle = "#2b2f3a"
crust = "#353b45"

# OS Module
[os]
disabled = false
style = "fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
PopOS = ""
RedHatEnterprise = "󱄛"

# Username Module
[username]
show_always = true
style_user = "fg:blue"
style_root = "fg:blue"
format = '[ $user ]($style)'

# Local IP Module
[localip]
ssh_only = false
style = "fg:surface0"
format = '[ $localipv4 ]($style)'
disabled = false

# Directory Module
[directory]
style = "fg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# Git Branch Module
[git_branch]
symbol = ""
style = "fg:teal"
format = '[[ $symbol $branch ](fg:green)]($style)'

# Git Status Module
[git_status]
style = "fg:teal"
format = '[[($all_status$ahead_behind )](fg:green)]($style)'

# Node.js Module
[nodejs]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# C Module
[c]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Rust Module
[rust]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Go Module
[golang]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# PHP Module
[php]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Java Module
[java]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Kotlin Module
[kotlin]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Haskell Module
[haskell]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Python Module
[python]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Lua Module
[lua]
symbol = "󰢱"
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Docker Context Module
[docker_context]
symbol = ""
style = "fg:mantle"
format = '[[ $symbol( $context) ](fg:color_bg3)]($style)'

# Time Module
[time]
disabled = false
time_format = "%R"
style = "fg:peach"
format = '[[  $time ](fg:purple)]($style)'

# Line Break Module
[line_break]
disabled = false

# Character Module
[character]
format = """
[$symbol](fg:overlay1) """
success_symbol = ' [➜](fg:bold text green)'
error_symbol = ' [×](fg:bold red)' 
